development:
  adapter: mysql2
  database: century21ap
  host: localhost
  username: root
  password: 

production:
  adapter: mysql2
  database: century21ap
  host: 127.0.0.1
  username: century21ap
  password: V@nil!a1cat